import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/bee-ui/__docusaurus/debug',
    component: ComponentCreator('/bee-ui/__docusaurus/debug', 'b87'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/config',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/config', '3cb'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/content',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/content', 'f72'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/globalData',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/globalData', 'd18'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/metadata',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/metadata', '5ff'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/registry',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/registry', '735'),
    exact: true
  },
  {
    path: '/bee-ui/__docusaurus/debug/routes',
    component: ComponentCreator('/bee-ui/__docusaurus/debug/routes', 'f1f'),
    exact: true
  },
  {
    path: '/bee-ui/help',
    component: ComponentCreator('/bee-ui/help', '9fb'),
    exact: true
  },
  {
    path: '/bee-ui/search',
    component: ComponentCreator('/bee-ui/search', '833'),
    exact: true
  },
  {
    path: '/bee-ui/docs',
    component: ComponentCreator('/bee-ui/docs', 'ac5'),
    routes: [
      {
        path: '/bee-ui/docs/intro',
        component: ComponentCreator('/bee-ui/docs/intro', 'cba'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/security',
        component: ComponentCreator('/bee-ui/docs/security', 'fbe'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/xirosoft/saiket',
        component: ComponentCreator('/bee-ui/docs/xirosoft/saiket', '09a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/xirosoft/sofiqul',
        component: ComponentCreator('/bee-ui/docs/xirosoft/sofiqul', '89a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '/bee-ui/',
    component: ComponentCreator('/bee-ui/', 'd7e'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
