import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/bee-ui/help',
    component: ComponentCreator('/bee-ui/help', '9fb'),
    exact: true
  },
  {
    path: '/bee-ui/search',
    component: ComponentCreator('/bee-ui/search', '833'),
    exact: true
  },
  {
    path: '/bee-ui/docs',
    component: ComponentCreator('/bee-ui/docs', 'bbf'),
    routes: [
      {
        path: '/bee-ui/docs/components/alert',
        component: ComponentCreator('/bee-ui/docs/components/alert', '210'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/background-color',
        component: ComponentCreator('/bee-ui/docs/components/background-color', '21e'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/badge',
        component: ComponentCreator('/bee-ui/docs/components/badge', 'aae'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/banner',
        component: ComponentCreator('/bee-ui/docs/components/banner', 'f5c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/button',
        component: ComponentCreator('/bee-ui/docs/components/button', 'b6a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/button-group',
        component: ComponentCreator('/bee-ui/docs/components/button-group', '86d'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/card',
        component: ComponentCreator('/bee-ui/docs/components/card', 'c84'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/checkbox',
        component: ComponentCreator('/bee-ui/docs/components/checkbox', 'e2c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/color-link',
        component: ComponentCreator('/bee-ui/docs/components/color-link', '5c1'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/form',
        component: ComponentCreator('/bee-ui/docs/components/form', 'ee0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/list',
        component: ComponentCreator('/bee-ui/docs/components/list', '28e'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/pagination',
        component: ComponentCreator('/bee-ui/docs/components/pagination', '281'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/components/team-section',
        component: ComponentCreator('/bee-ui/docs/components/team-section', 'e18'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/intro',
        component: ComponentCreator('/bee-ui/docs/intro', 'cba'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/security',
        component: ComponentCreator('/bee-ui/docs/security', 'fbe'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/xirosoft/saiket',
        component: ComponentCreator('/bee-ui/docs/xirosoft/saiket', '09a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/bee-ui/docs/xirosoft/sofiqul',
        component: ComponentCreator('/bee-ui/docs/xirosoft/sofiqul', '89a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '/bee-ui/',
    component: ComponentCreator('/bee-ui/', 'd7e'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
